
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
`timescale 1 ps / 1 ps
module tb_L();
  wire	    [19:0]		SRAM_ADDR;
	wire		          		SRAM_CE_N;
	wire 		    [15:0]		SRAM_DQ;
	wire		          		SRAM_LB_N;
	wire		          		SRAM_OE_N;
	wire		          		SRAM_UB_N;
	wire		          		SRAM_WE_N;
  reg [7:0] R,G,B;
  reg write, clk, rst;
  
  SRAM_INTERFACE sram_interface(
		.SRAM_DQ(SRAM_DQ),       // external_interface.DQ
		.SRAM_ADDR(SRAM_ADDR),     //                   .ADDR
		.SRAM_LB_N(SRAM_LB_N),     //                   .LB_N
		.SRAM_UB_N(SRAM_UB_N),     //                   .UB_N
		.SRAM_CE_N(SRAM_CE_N),     //                   .CE_N
		.SRAM_OE_N(SRAM_OE_N),     //                   .OE_N
		.SRAM_WE_N(SRAM_WE_N),     //                   .WE_N
    .R(R),.G(G),.B(B),
    .rst(rst), .clk(clk), .write(write));
    
  initial
  begin
    R= 8'h19;
    G= 8'h29;
    B= 8'h39;
    clk = 1'b0;
    write = 1'b0;
    rst = 1'b0;
    #500 rst = 1'b1;
    #100 rst = 1'b0;
    #300 write = 1'b1;
    #1000 write = 1'b0;
    #1000 write = 1'b1;
    #1000 write = 1'b0;
  end
  
  always #50 clk = ~clk;
   
endmodule
